# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/sayed/Desktop/Programing/major project/major-project-/adder/adder.cache/wt} [current_project]
set_property parent.project_path {C:/Users/sayed/Desktop/Programing/major project/major-project-/adder/adder.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/adder/adder.srcs/sources_1/new/DEFAULT_ADDER.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/adder/adder.srcs/sources_1/new/COVER_DEFAULT_ADDER.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}]


synth_design -top COVER_DEFAULT_ADDER -part xc7k160tffg676-1


write_checkpoint -force -noxdef COVER_DEFAULT_ADDER.dcp

catch { report_utilization -file COVER_DEFAULT_ADDER_utilization_synth.rpt -pb COVER_DEFAULT_ADDER_utilization_synth.pb }
