# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/sayed/Desktop/Programing/major project/major-project-/misc/misc.cache/wt} [current_project]
set_property parent.project_path {C:/Users/sayed/Desktop/Programing/major project/major-project-/misc/misc.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/sayed/Desktop/Documents and downloads/m2VG_pipelined_2.v}
  {C:/Users/sayed/Desktop/Documents and downloads/m4VG.v}
  {C:/Users/sayed/Desktop/Documents and downloads/m8VG.v}
  {C:/Users/sayed/Desktop/Documents and downloads/m16VG.v}
  {C:/Users/sayed/Desktop/Documents and downloads/m32VG.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}]


synth_design -top m32VG_pipelined -part xc7k70tfbv676-1


write_checkpoint -force -noxdef m32VG_pipelined.dcp

catch { report_utilization -file m32VG_pipelined_utilization_synth.rpt -pb m32VG_pipelined_utilization_synth.pb }
