# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/sayed/Desktop/Programing/major project/major-project-/misc/misc.cache/wt} [current_project]
set_property parent.project_path {C:/Users/sayed/Desktop/Programing/major project/major-project-/misc/misc.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/m2VG_pipelined_2.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/m4VG.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/m8VG.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/m16VG.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/Absoluter_adder.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/NormaliserW.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/subtract_2.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/m32VG.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/adderW2.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/Absoluter_32.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/NormaliseWc.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/Subtractor_pipelined.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/subtractor_32.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/emsggen.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/AdderWc_pipelined.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/recovunit_dp.v}
  {C:/Users/sayed/Desktop/Documents and downloads/ne_RCU/E_mem_ne_bram.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/SISO_rowunit.v}
  {C:/Users/sayed/Desktop/Programing/major project/major-project-/NE_rpu/SISO_rowunit_cover.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/sayed/Desktop/Documents and downloads/design_constr.xdc}}]


synth_design -top SISO_rowunit_cover -part xc7k70tfbv676-1


write_checkpoint -force -noxdef SISO_rowunit_cover.dcp

catch { report_utilization -file SISO_rowunit_cover_utilization_synth.rpt -pb SISO_rowunit_cover_utilization_synth.pb }
