@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 18 21:14:04 +0530 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim rowcomputer_tb_behav -key {Behavioral:sim_1:Functional:rowcomputer_tb} -tclbatch rowcomputer_tb.tcl -log simulate.log"
call xsim  rowcomputer_tb_behav -key {Behavioral:sim_1:Functional:rowcomputer_tb} -tclbatch rowcomputer_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
